# Generated by Django 6.0.1 on 2026-01-26 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails/'),
        ),
    ]
