# Generated by Django 6.0.1 on 2026-01-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_director_movie_duration_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_type',
            field=models.CharField(choices=[('film', 'Film'), ('anime', 'Anime'), ('serie', 'Série')], default='film', max_length=10),
        ),
    ]
