# Generated by Django 6.0.1 on 2026-01-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_video_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_movies',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='movies.movie'),
        ),
    ]
