# Generated by Django 6.0.1 on 2026-01-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.movie'),
        ),
    ]
