# Generated by Django 6.0.1 on 2026-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_comment_rating_watchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
