# Generated by Django 6.0.1 on 2026-01-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.PositiveIntegerField(default=1, verbose_name="Numéro d'épisode"),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, verbose_name='Est une série'),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Numéro de saison'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie', verbose_name='Série parente'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sous-titre'),
        ),
    ]
