# Generated by Django 6.0.1 on 2026-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_episode_number_movie_is_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_series',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series_parent',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drame'), ('comedy', 'Comédie'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('fantasy', 'Fantaisie'), ('horror', 'Horreur'), ('sci_fi', 'Science-Fiction')], default='action', max_length=20),
        ),
    ]
