# Generated by Django 6.0.1 on 2026-01-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_episode_number_remove_movie_is_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(default=1)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='episodes/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(limit_choices_to={'video_type__in': ['serie', 'anime']}, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Épisode',
                'verbose_name_plural': 'Épisodes',
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('movie', 'season_number', 'episode_number')},
            },
        ),
    ]
