# Generated by Django 6.0.1 on 2026-01-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drame'), ('comedy', 'Comédie'), ('romance', 'Romance'), ('horror', 'Horreur')], default='action', max_length=20),
        ),
    ]
